### PR TITLE
Update gitignore for mac OS files

### PR DESCRIPTION
**Pull request by tomanderson2**
ignore common mac files

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
@tomanderson2 I haven't seen the question mark in `.gitignore` before, thanks for pointing that out.  Why have one trail `.DS_Store`, though?  I haven't seen that happen before.

**Comment by ajnelson-nist** [comment]
Actually, I've never seen `.DS_Store` named anything except exactly that.  Where does that vary?

**Comment by tomanderson2** [comment]
@ajnelson-nist I'll be honest and say I don't know... I've been using those same .gitignore values for mac on projects for a while now and just copy / pasted it from one on my machine. 

The official github gitignore doesn't include it, but others (like this which is the second hit in google https://gist.github.com/pcstl/d118342ef049a086fb555c9795beb4ba) do.

I can remove it for now to avoid any issues

**Comment by ajnelson-nist** [comment]
Huh.  That gist points at this repository, where I would expect the pattern to appear in the macos file...
https://github.com/github/gitignore/blob/master/Global/macOS.gitignore

For now, please reduce the `.DS_Store` lines to just spell exactly `.DS_Store`.

**Comment by ajnelson-nist** [comment]
@tomanderson2 I added one follow-on commit to reduce the chance of files looking like `.DS_Store` being ignored.

Thanks for the patch!

**Pull request merged**
