### PR TITLE
Start coverage-illustration page for intervals of existence

### PR DESCRIPTION
**Pull request by ajnelson-nist**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
This PR is provided to set up an illustration in support of coming discussion on time representations.

The PR is ready for review and merge when CI has completed.

**Comment by ajnelson-nist** [comment]
Apologies, one update pushed to fix something caught by CI.

**Comment by ajnelson-nist** [comment]
The PR has been updated to include OWL-Time.

**Review by plbt5 — APPROVED** [review]
Impressive work!

**Pull request merged**
